#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2019-2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

"""
pbe - a tool for measuring C-states power break even.
"""

from wulttools.pbe._Pbe import main

if __name__ == "__main__":
    raise SystemExit(main())
